name = "SanzoWada"
uuid = "e845086f-eff8-42ae-b00d-3c1b804da6e1"
authors = ["Søren Post"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
